# Generated by Django 5.0.2 on 2024-03-15 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0034_remove_settings_favicon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settings",
            name="siteemail",
            field=models.CharField(default="qfs@mail.com", max_length=100),
        ),
        migrations.AlterField(
            model_name="settings",
            name="sitename",
            field=models.CharField(default="qfs", max_length=100),
        ),
    ]
