# Generated by Django 5.0.2 on 2024-03-21 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0035_alter_settings_siteemail_alter_settings_sitename"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="cardcreate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cardtype", models.CharField(max_length=100)),
                ("uniqcode1", models.IntegerField(default=1111)),
                ("uniqcode2", models.IntegerField(default=2222)),
                ("uniqcode3", models.IntegerField(default=3333)),
                ("uniqcode4", models.IntegerField(default=4444)),
                ("secretpin", models.IntegerField(default=120)),
                ("amount", models.FloatField(default=0.0)),
                ("expdate", models.DateField()),
                ("logo", models.ImageField(upload_to="photos/%y")),
            ],
        ),
        migrations.CreateModel(
            name="cardpay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paymentmethod", models.CharField(max_length=100)),
                ("status", models.BooleanField(default=False)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.cardcreate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
