# Generated by Django 5.0.2 on 2024-03-27 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0036_cardcreate_cardpay"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="charity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="photos/%y")),
                ("reason", models.CharField(max_length=1000)),
                ("percentage", models.IntegerField(default=1)),
                ("raised", models.FloatField(default=0.0)),
                ("goal", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="charitypayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan", models.CharField(max_length=100)),
                ("cryptoname", models.CharField(max_length=100)),
                ("cryptoamount", models.FloatField(default=0.0)),
                ("status", models.BooleanField(default=False)),
                (
                    "charity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.charity"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="giftcardpay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan", models.CharField(max_length=100)),
                ("giftcardname", models.CharField(max_length=100)),
                ("giftcardcode", models.IntegerField()),
                ("giftcardamount", models.FloatField()),
                ("giftcardimg", models.ImageField(upload_to="")),
                ("status", models.BooleanField(default=False)),
                (
                    "charity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.charity"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
